services:
  nginx:
    image: nginx:latest
    ports:
      - ${DOCKER_NGINX_PORT}:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/srv/app
      - php_socket:/var/run/php
    networks:
      - test-app-network

  php:
    build:
      context: .
      target: app_php
      args:
        APP_ENV: ${APP_ENV}
        NODE_VERSION: ${NODE_VERSION}
    restart: unless-stopped
    volumes:
      - php_socket:/var/run/php
    environment: [ ]
    networks:
      - test-app-network

  mysql:
    image: mysql:8.0.33
    ports:
      - ${DOCKER_DB_PORT}:3306
    volumes:
      - ./db_data:/var/lib/mysql
      - ./docker/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - test-app-network

volumes:
  php_socket:

networks:
  test-app-network:
    driver: bridge
